mlmd_config: {
  sqlite: {
    filename_uri: "mlmd-bench-nbvcxsreytu.db"
    connection_mode: READWRITE_OPENCREATE
  }
  retry_options: {
    max_num_retries: 1000000000000
  }
}
workload_configs: { 
  fill_types_config: {
  update: false
  specification: ARTIFACT_TYPE
  num_properties: { minimum: 1 maximum: 10 }
  }
  num_operations: 200
}
workload_configs: { 
  fill_types_config: {
  update: true
  specification: ARTIFACT_TYPE
  num_properties: { minimum: 1 maximum: 10 }
  }
  num_operations: 1000
}
thread_env_config: { num_threads: 10 }
